
spring.application.name=FreshDesk
server.port=8080


freshdesk.base.url=https://thearushi16-help.freshdesk.com/api/v2


freshdesk.api.key=K7VY0lFSI70ocbjkaIoI


spring.jackson.serialization.indent_output=true